[workspace]
members = ["limnifs-format", "limnifs-core", "limnifs-conformance", "limnifs-write", "limni"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/limnifs/limnifs"
homepage = "https://www.limnifs.org"
description = "LimniFS — Layered, Immutable, Merkle-rooted, Network Image filesystem"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = "warn"

[workspace.dependencies]
blake3 = { version = "1.5", default-features = false, features = ["std"] }
chacha20poly1305 = { version = "0.10", default-features = false, features = ["alloc", "getrandom"] }
clap = { version = "4.5", features = ["derive", "string"] }
getrandom = "0.2"
hkdf = { version = "0.12", default-features = false }
lz4_flex = { version = "0.11", default-features = false, features = ["std"] }
rand_core = { version = "0.6", default-features = false }
sha2 = { version = "0.10", default-features = false }
x25519-dalek = { version = "2.0", default-features = false, features = ["static_secrets", "getrandom"] }
