[package]
name = "limni"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "LimniFS CLI — one format, one CLI"

[[bin]]
name = "limni"
path = "src/main.rs"

[dependencies]
limnifs-core = { path = "../limnifs-core", version = "0.2.48", features = ["signing"] }
limnifs-write = { path = "../limnifs-write", version = "0.2.48" }
clap.workspace = true
fuser = { version = "0.18", optional = true, default-features = false }
getrandom.workspace = true
rayon.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
fuser = { version = "0.18", optional = true, default-features = false, features = ["macos-no-mount"] }

[features]
default = []
fuse = ["dep:fuser"]

[lints]
workspace = true
