[package]
name = "limni"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "LimniFS CLI — one format, one CLI"

[[bin]]
name = "limni"
path = "src/main.rs"

[dependencies]
limnifs-core = { workspace = true, features = ["signing"] }
serde = { workspace = true }
serde_json = { workspace = true }
limnifs-write.workspace = true
clap.workspace = true
fuser = { version = "0.18", optional = true, default-features = false }
getrandom.workspace = true
rayon.workspace = true
tar = { version = "0.4", optional = true, default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
fuser = { version = "0.18", optional = true, default-features = false, features = ["macos-no-mount"] }

[features]
default = []
fuse = ["dep:fuser"]
tar = ["dep:tar"]
sparse-index = ["limnifs-write/sparse-index"]

[lints]
workspace = true
